### ISSUE TITLE
Autocomplete / View: autocomplete is slow when returning large datasets

### ISSUE THREAD

**Issue by AireL** [ocadotechnology/hexagonjs#148]
Tried using it with a large dataset (5000+) - when returning a significant chunk of that data the page would lock up for seconds while trying to render the page

**Comment by c-frater** [comment]
This looks to be a problem related to `hx.View` and #14 (fixed in #57) which has [added a check to the view](https://github.com/ocadotechnology/hexagonjs/blob/master/modules/view/main/index.coffee#L75-L78), slowing it down. Is there any way to improve performance for the check @jmsmyth @georgesimms ?

**Comment by jmsmyth** [comment]
The `selectAll` can be avoided - checking the `element.nodeName` and `classes` of the new element match the selector and checking that `rootSelection.node().contains(element)` could be faster.

Also the new function can be optimised a bit [on this line](https://github.com/ocadotechnology/hexagonjs/blob/master/modules/view/main/index.coffee#L6) by moving the deconstruction of the selector out of the new function

Not sure if that will be enough though, since 5000+ is quite a lot of nodes. Perhaps just showing the top n results (where n is a smallish number) could work. If not, someone might need to implement #17?

**Comment by georgesimms** [comment]
There's an implicit suggestion here that the view selection is relatively simple (like `element-type.class-1.class-2` or something). This is OK I guess but we should be honest about it.

Also we may want to disable the warning when the default view enter function is used.
