### ISSUE TITLE
Form Builder / Picker - after clearing value from required field form validation passes on submit

### ISSUE THREAD

**Issue by Tomasz-Zlamaniec** [ocadotechnology/hexagonjs#304]
Hexagon version: 1.6.0
## Expected

A form is created with a required picker. When user tries to submit the form then validation error is shown because the value is empty. After setting the value the form can be submitted. After submitting the form the value is removed using `form.value(field, undefined)`, when the user submits the form again the validation error should be shown.
## Actual

If form passes validation with a value in picker and the value is removed problematically then next validation will pass even though the required field has no value.
## Example

```
const FIELD = "My Field";

var form = new hx.Form('#form')
    .addPicker(FIELD, ["A", "B", "C"], {required: true})
    .addSubmit("Submit");

form.on("submit", () => setTimeout(() => form.value(FIELD, undefined), 2000));
```

Select a value, click submit, wait 2 seconds, click submit again and there is no validation error:

![image](https://cloud.githubusercontent.com/assets/20813116/18306481/f4e5b016-74e3-11e6-9a24-63830a257995.png)

**Comment by c-frater** [comment]
This is because the picker is not correctly re-setting the validation message. Updating the `setCustomValidity` to be `hx.userFacingText('form', 'pleaseSelectAValue')` when the value from the `change` event is undefined
https://github.com/ocadotechnology/hexagonjs/blob/master/modules/form-builder/main/index.coffee#L124
