### ISSUE TITLE
Crumbtrail: items getter doesn't work

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#309]
```
hx.select('#crumbs-2').component() // => returns ['First Node', 0, 'Second Node', 0, 'Third Node'], expected ['First Node', 'Second Node', 'Third Node']
```

**Comment by c-frater** [comment]
The reason for this is because a flat `view` is being used to render the items and `0` is being pushed into the array to render the separator.

Example:
```js
var items = [
  'bob',
  'steve',
  'dave'
]

var crumbtrail = new hx.Crumbtrail(hx.detached('div').node(), {
  items: items
})
crumbtrail.items()
```

The easiest solution for this is not to store the modified list and instead apply the new list directly:
https://github.com/ocadotechnology/hexagonjs/blob/master/modules/crumbtrail/main/index.coffee#L37
```
@options.items = data
@view.apply hx.flatten(data.map((d) -> [d, 0])).slice(0, -1)
```
